export class ParamsArray {
  public static COUSINES = [
    // 'African',
    "American",
    // 'British',
    // 'Cajun',
    // 'Caribbean',
    "Chinese",
    // 'Eastern European',
    "European",
    // 'French',
    // 'German',
    "Greek",
    "Indian",
    // 'Irish',
    "Italian",
    "Japanese",
    // 'Jewish',
    "Korean",
    "Latin American",
    // 'Mediterranean',
    "Mexican",
    // 'Middle Eastern',
    // 'Nordic',
    // 'Southern',
    "Spanish",
    "Thai",
    // 'Vietnamese',
  ];

  public static DIETS = [
    "Gluten Free",
    "Ketogenic",
    "Vegetarian",
    // 'Lacto-Vegetarian',
    // 'Ovo-Vegetarian',
    "Vegan",
    // 'Pescetarian',
    // 'Paleo',
    "Primal",
    "Whole30",
  ];

  public static INTOLERANCES = [
    "Dairy",
    "Egg",
    "Gluten",
    "Grain",
    "Peanut",
    "Seafood",
    "Sesame",
    // 'Shellfish',
    // 'Soy',
    "Sulfite",
    // 'Tree Nut',
    "Wheat",
  ];

  public static TYPES = [
    // 'main course',
    "side dish",
    "dessert",
    "appetizer",
    "salad",
    "bread",
    "breakfast",
    "soup",
    // 'beverage',
    "sauce",
    // 'marinade',
    // 'fingerfood',
    "snack",
    "drink",
  ];
}
